name: Build and lint code
description: Action that installs dependencies, builds and lints the code
branding:
  icon: 'check'
  color: 'green'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'pnpm'
    - name: Install modules
      run: pnpm
      shell: bash
    - name: Build code
      run: pnpm build
      shell: bash
    - name: Lint code
      run: pnpm lint
      shell: bash
